# Generated by Django 4.2.2 on 2023-07-05 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Not Viewed', 'not_viewed'), ('Accept', 'accept'), ('Reject', 'reject')], default=0, max_length=128, verbose_name='status_feedback')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True)),
                ('text', models.TextField()),
                ('file_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('file_video', models.FileField(blank=True, null=True, upload_to='video')),
                ('file_audio', models.FileField(blank=True, null=True, upload_to='audio')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryThrough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletin_board.category')),
                ('postThrough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletin_board.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='postCategory',
            field=models.ManyToManyField(through='bulletin_board.PostCategory', to='bulletin_board.category'),
        ),
        migrations.CreateModel(
            name='FeedbackPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedbackThrough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletin_board.feedback')),
                ('postThrough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletin_board.post')),
            ],
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedbackPost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bulletin_board.post'),
        ),
    ]
